# Generated by Django 3.1.3 on 2020-12-13 17:53

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name=polls.models.Question)),
                ('comment', models.CharField(max_length=50)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
