# Generated by Django 3.1.3 on 2020-12-27 16:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(default='DEFAULT VALUE', storage=django.core.files.storage.FileSystemStorage(location='/archive/polls/'), upload_to=''),
        ),
    ]
